apiVersion: apps/v1
kind: Deployment
metadata:
  name: arc-k8s-demo2
  labels:
    app: arc-k8s-demo2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arc-k8s-demo2
  template:
    metadata:
      labels:
        app: arc-k8s-demo2
    spec:
      containers:
      - name: arc-k8s-demo2
        image: demoreg4433.azurecr.io/webappkubernetes:latest
        ports:
        - containerPort: 80
